name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: .github/ci-build.sh

      - name: Upload binary
        uses: actions/upload-artifact@v1
        with:
          name: templeos-loader
          path: cmake-build-debug/templeos-loader
